Repository openshift/openshift-ansible-contrib, pull requests merged in 2018-06, with the labels that each got.

#1040 Clarify Inventory Directory Location
  reference-architecture/rhv-ansible/README.md
Labels: rhv

#1042 RHOCP on AWS 3.9 - One user-data to rule them all
  reference-architecture/3.9/playbooks/roles/aws/files/ec2_userdata_bastion.sh
  reference-architecture/3.9/playbooks/roles/aws/files/ec2_userdata_master.sh
  reference-architecture/3.9/playbooks/roles/aws/files/ec2_userdata_node.sh
  reference-architecture/3.9/playbooks/roles/aws/tasks/ec2.yaml
  reference-architecture/3.9/playbooks/roles/aws/tasks/ec2_cns.yaml
  reference-architecture/3.9/playbooks/roles/aws/templates/ec2_userdata.sh.j2
Labels: size/L

#1007 fix symlinks
  playbooks/library/rpm_q.py
  reference-architecture/aws-ansible/playbooks/library/rpm_q.py
  reference-architecture/vmware-ansible/playbooks/library/rpm_q.py
Labels: aws, vmware

#1048 oreg_url fix for bz 1588768
  reference-architecture/rhv-ansible/example/inventory
  reference-architecture/rhv-ansible/example/inventory.yaml
Labels: rhv, size/XS

#1051 Changed style of fix along with kb 3480921
  reference-architecture/rhv-ansible/example/inventory
  reference-architecture/rhv-ansible/example/inventory.yaml
Labels: size/XS

#1047 feature req issue #1046
  reference-architecture/3.9/README.md
  reference-architecture/3.9/playbooks/roles/aws/tasks/getec2ami.yaml
  reference-architecture/3.9/playbooks/vars/main.yaml
  reference-architecture/aws-ansible/README.md
Labels: size/M

#1053 Remove custom setting from extra_vars
  reference-architecture/3.9/playbooks/vars/main.yaml
Labels: size/XS

#1055 Fix to static domain in r53 query
  reference-architecture/3.9/playbooks/roles/aws/tasks/configfilesdata.yaml
Labels: size/XS

#1057 [AWS ref arch] Fix dns internal record for router
  reference-architecture/3.9/playbooks/roles/aws/tasks/route53record.yaml
Labels: size/XS

#1060 Added wrapper scripts and instructions for 3.9
  reference-architecture/gcp/3.9/README.md
  reference-architecture/gcp/3.9/bastion.sh
  reference-architecture/gcp/3.9/bastion.vars
  reference-architecture/gcp/3.9/create_infrastructure.sh
  reference-architecture/gcp/3.9/delete_infrastructure.sh
  reference-architecture/gcp/3.9/infrastructure.vars
Labels: size/XXL
